// 课程事实取自下列官方页面；学习重点是本工具的选学建议，不是官方就业承诺。
export const verifiedOn='2026-10-07';
export const courses=[
 {id:'ml-intro',title:'机器学习简介',provider:'Google',url:'https://developers.google.com/machine-learning/intro-to-ml?hl=zh-cn',language:'中文页面',format:'概念入门课程',prerequisite:'可以先从概念入门。',focus:'先理解机器学习是什么、有哪些任务；暂不要求写训练代码。',topics:['人工智能','机器学习','模型基础'],level:'入门'},
 {id:'python',title:'CS50’s Introduction to Programming with Python',provider:'Harvard CS50',url:'https://cs50.harvard.edu/python/',language:'英文授课与资料',format:'视频与练习',prerequisite:'官方面向有或没有编程经验的学习者。',focus:'先学Functions / Variables、Conditionals、Loops；再学Exceptions、Libraries、File I/O。做相应练习，不只看视频。',topics:['Python','编程','数据处理'],level:'入门'},
 {id:'sql',title:'使用 Transact-SQL 查询和修改数据',provider:'Microsoft Learn',url:'https://learn.microsoft.com/zh-cn/training/paths/get-started-querying-with-transact-sql/',language:'中文',format:'分模块教程与练习',prerequisite:'先熟悉表格中的行、列与数据。',focus:'先学SELECT、排序筛选、JOIN和GROUP BY。课程使用T-SQL，其他数据库的细节语法可能不同。',topics:['SQL','查数','数据分析'],level:'入门'},
 {id:'genai',title:'生成式AI入门课程',provider:'Microsoft',url:'https://github.com/microsoft/generative-ai-for-beginners/blob/main/translations/zh-CN/README.md',language:'简体中文翻译',format:'概念课程与代码练习',prerequisite:'先读概念课；代码练习需要Python或TypeScript基础及相应运行环境。',focus:'先选第1课生成式AI简介、第4课提示工程基础；有编程基础后，再选第15课RAG、第17课Agent、第18课微调。',topics:['大模型','Prompt','提示词','RAG','Agent','微调'],level:'概念入门／实作需基础'},
 {id:'ml-crash',title:'机器学习速成课程',provider:'Google',url:'https://developers.google.com/machine-learning/crash-course/prereqs-and-prework?hl=zh-cn',language:'中文页面',format:'概念课程与编程练习',prerequisite:'需要代数、统计基础和编程能力；练习使用Python。',focus:'补齐前置知识后学分类、数据集与过拟合，再看神经网络。先用小例子练习解释指标。',topics:['模型评估','精确率','召回率','分类','神经网络'],level:'补基础后再学'},
 {id:'agents',title:'AI Agents Course',provider:'Hugging Face',url:'https://huggingface.co/learn/agents-course/en/unit0/introduction',language:'此入口为英文',format:'理论与实作课程',prerequisite:'官方要求Python基础和大语言模型基础。',focus:'先学Unit 1 Agent Fundamentals，再选一个框架与一个应用案例；不必同时学习全部框架。',topics:['Agent','Tools','工具调用','框架','RAG'],level:'补基础后再学'},
 {id:'llm',title:'LLM Course：Transformer与微调',provider:'Hugging Face',url:'https://huggingface.co/learn/llm-course/zh-CN/chapter1/1',language:'中文课程页面',format:'教程与代码练习',prerequisite:'官方要求良好的Python知识，建议先完成入门深度学习课程。',focus:'第1章理解Transformer，第2章学习模型使用，第3章再做预训练模型微调。不能直接跳过Python基础。',topics:['Transformer','NLP','微调','训练'],level:'之后深入'},
 {id:'user-needs',title:'Learning about users and their needs',provider:'GOV.UK Service Manual',url:'https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs',language:'英文',format:'用户研究指南（非完整课程）',prerequisite:'无需编程；结合自己能接触的真实用户练习。',focus:'阅读理解、研究、书写与验证用户需求的部分。区分用户证据与自己的假设。',topics:['业务理解','用户访谈','产品需求','产品经理'],level:'入门'}
].map(c=>({...c,verified_on:verifiedOn}));
export const courseById=new Map(courses.map(c=>[c.id,c]));
